### ISSUE TITLE
500 Error when setting up the RSS template

### ISSUE THREAD

**Issue by krelde** [enonic/app-rss#18]
I get the following error when setting up the RSS template:
![image](https://cloud.githubusercontent.com/assets/18183713/23612223/d44446a4-027a-11e7-84ad-0879c3d7f8e9.png)

![image](https://cloud.githubusercontent.com/assets/18183713/23612241/f7557820-027a-11e7-815c-25c5e504197b.png)

**Comment by Bellfalasch** [comment]
Yes, it will be solved with issue #16 and with pull request #17

**Comment by krelde** [comment]
Oh sorry didn't see #16. But i should still be able to setup and use the feed?

**Comment by Bellfalasch** [comment]
Yes, just create a new content of type RSS after the template is saved (and it must have setting for "supports: rss". Then, when viewing this new content all will work.
