### ISSUE TITLE
Implement SY Update period/frequency

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-rss#3]
Actually use the fields/settings for update period and frequency. With override support from the app itself.

SY Update period
SY Update frequency

**Comment by pvmerlo** [comment]
Just to understand: lets suppose I've set the update period to hourly and frequency 1x. If my rss feed was updated on 12:01, and between this time and 12:59 I've created a new article. This new content will be available on the rss feed just after the next update (in this case, at 13:00)?

**Comment by Bellfalasch** [comment]
It doesn't do anything magical, it just adds some meta data to the feed that feed readers can use ... if they like to. As we did in superhero blog we just selected between multiple predefined options (see rss page xml and site xml) and then used that as is. That's the thing I had in mind here.

Alternative is to remove it. Actually not sure if it is of any value to have it.

What you describe is not in the scope of this task. Perhaps if cache was implemented ... but that all feels more like something for the future 2.0.
