### ISSUE TITLE
Support author tag in RSS

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-rss#5]
Needs mapping to find where name of author is stored ... not very simple probably. But the RSS tags are there if we want to use them.

**Comment by pvmerlo** [comment]
In the solution I'm working now, the Author follows some logic. If the Author name/email is not set on the article content, it's taken from the creator of it. We should do the same?

**Comment by Bellfalasch** [comment]
Perhaps, using the actual author as in XP is a good thing since that data is always available. Makes it easier to have something to fallback on. Good suggestion!
