### ISSUE TITLE
Implement Category tags in RSS feed

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-rss#6]
Use the RSS feature of adding category data to each feed item.

**Comment by pvmerlo** [comment]
In the solution I'm working now, we use category as a relationship, but XP has a "Tag" input type that I think  that's used in other sites as categories of each post too. We should handle these two type of categories, as objects and tag-like, right?

**Comment by Bellfalasch** [comment]
It's problematic since it can be implemented in any of these ways and that's why I haven't planned this feature for 1.0 release. But at least it is a bit more important than author, and hopefully simpler to add. Using the tags data type I already have code for, in the superhero theme. I just wonder how to best implement the field mapping for this ... might need some extra config.

**Comment by pvmerlo** [comment]
I think we don't need extra configs. We can just watch the field for categories if it matches to a list of ids (using the regex "\/\/\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/g") or simple texts, in case of Tag input-type. What do you think about this approach?

**Comment by Bellfalasch** [comment]
That is true, with that being there (a id/key) we can "just" do a content.get() on it and display it's displayName. That's a good approach. If not a id/key the field can be used as is (as string).
